# Generated by Django 5.2.1 on 2025-05-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to='backups/')),
                ('tipo', models.CharField(choices=[('Completo', 'Completo'), ('Diferencial', 'Diferencial')], max_length=50)),
                ('estado', models.CharField(choices=[('En Proceso', 'En Proceso'), ('Completado', 'Completado'), ('Fallido', 'Fallido')], default='En Proceso', max_length=50)),
            ],
        ),
    ]
