# Generated by Django 5.2.1 on 2025-05-23 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0003_backupactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Backup',
        ),
        migrations.AlterModelOptions(
            name='backupactivity',
            options={'ordering': ['-fecha'], 'verbose_name': 'Actividad de Backup', 'verbose_name_plural': 'Actividades de Backup'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nombre'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='backupactivity',
            name='detalle',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle adicional'),
        ),
        migrations.AlterField(
            model_name='backupactivity',
            name='accion',
            field=models.CharField(max_length=255, verbose_name='Acción realizada'),
        ),
        migrations.AlterField(
            model_name='backupactivity',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la acción'),
        ),
        migrations.AlterField(
            model_name='backupactivity',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema'),
        ),
    ]
