# Generated by Django 5.2.1 on 2025-05-23 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0004_delete_backup_alter_backupactivity_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.DeleteModel(
            name='BackupActivity',
        ),
    ]
