# Generated by Django 5.2.1 on 2025-05-23 02:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0005_alter_usuario_options_delete_backupactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('archivo', models.CharField(max_length=200)),
            ],
        ),
    ]
