# Generated by Django 5.2.1 on 2025-05-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0006_backupregistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_backup', models.TimeField(help_text='Hora del día para ejecutar el backup automático')),
                ('activa', models.BooleanField(default=True, help_text='Indica si el backup automático está activo')),
            ],
        ),
    ]
