# Generated by Django 5.2.1 on 2025-05-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0007_backupconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='numero',
            field=models.CharField(default=123345567789, max_length=100),
            preserve_default=False,
        ),
    ]
