# Generated by Django 5.2.1 on 2025-05-27 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0008_usuario_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='numero',
        ),
    ]
