# Generated by Django 5.2.1 on 2025-05-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0009_remove_usuario_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('tecnico', 'Técnico'), ('usuario', 'Usuario')], default='usuario', max_length=10),
        ),
    ]
